"""Shared types and structural interfaces for the admin CLI.

The CLI splits into rendering, completion, form and layout modules. These modules
must not import the orchestrator directly. They depend on these protocols instead,
which keeps the import graph acyclic. The completer reads a `CompleterHost`. The
form and log components speak to an `AppContext`. The layout and the key bindings
drive an `AppView`.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from prompt_toolkit.buffer import Buffer
from prompt_toolkit.formatted_text import StyleAndTextTuples
from prompt_toolkit.mouse_events import MouseEvent

from .models import Choices, Form

# A handler runs a parsed slash-command from its positional arguments.
Handler = Callable[[list[str]], None]
# An option provider returns the completions for the token that the user types.
Options = Callable[[list[str]], list[str]]
# A prompt_toolkit per-fragment mouse handler.
MouseHandler = Callable[[MouseEvent], object]


class CompleterHost(Protocol):
    """What the command completer reads from the orchestrator."""

    def command_names(self) -> list[str]:
        """Return every slash-command that the CLI offers."""
        ...

    def argument_options(self, parts: list[str]) -> list[str]:
        """Return the completions for the argument token that the user types."""
        ...


class AppContext(Protocol):
    """The orchestrator surface the log and form components depend on."""

    @property
    def buffer(self) -> Buffer: ...

    def info(self, text: str) -> None:
        """Append an informational line to the log."""
        ...

    def error(self, text: str) -> None:
        """Append an error line to the log."""
        ...

    def invalidate(self) -> None:
        """Request a repaint."""
        ...


class EditorPanelView(Protocol):
    """A modal field-editor panel (the form dialog)."""

    def showing(self) -> bool: ...
    def fragments(self) -> StyleAndTextTuples: ...
    def title(self) -> str: ...
    def move(self, delta: int) -> None: ...
    def change(self, delta: int) -> None: ...
    def type_char(self, text: str) -> None: ...
    def backspace(self) -> None: ...
    def submit(self) -> None: ...
    def cancel(self) -> None: ...


class LogPanelView(Protocol):
    """The scrolling log panel: its fragments, floats and scroll state."""

    def log_fragments(self) -> StyleAndTextTuples: ...
    def completion_fragments(self) -> StyleAndTextTuples: ...
    def detail_fragments(self) -> StyleAndTextTuples: ...
    def detail_title(self) -> str: ...
    def showing_detail(self) -> bool: ...
    def scrolled_up(self) -> bool: ...
    def close_detail(self) -> None: ...
    def scroll_log(self, delta: int) -> None: ...
    def scroll_to_bottom(self) -> None: ...
    def log_height(self) -> int: ...


class AppView(Protocol):
    """What the layout renders and the key bindings drive."""

    @property
    def buffer(self) -> Buffer: ...
    @property
    def logs(self) -> LogPanelView: ...
    @property
    def form_panel(self) -> EditorPanelView: ...

    def toolbar(self) -> StyleAndTextTuples: ...
    def selector_fragments(self) -> StyleAndTextTuples: ...
    def selector_title(self) -> str: ...
    def line_prefix(self, line_number: int, wrap_count: int) -> StyleAndTextTuples: ...
    def scroll_button_fragments(self) -> StyleAndTextTuples: ...

    def showing_selector(self) -> bool: ...
    def selector_searchable(self) -> bool: ...
    def selector_move(self, delta: int) -> None: ...
    def selector_pick(self, index: int | None = ...) -> None: ...
    def selector_pick_visible(self, position: int) -> None: ...
    def selector_type(self, text: str) -> None: ...
    def selector_backspace(self) -> None: ...
    def selector_cancel(self) -> None: ...

    def open_form(self, form: Form) -> None: ...

    def choose(
        self,
        title: str,
        values: Choices,
        on_choose: Callable[[str | None], None],
        *,
        searchable: bool = ...,
    ) -> None: ...


__all__ = [
    "Handler",
    "Options",
    "MouseHandler",
    "CompleterHost",
    "AppContext",
    "EditorPanelView",
    "LogPanelView",
    "AppView",
]
